<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');
    
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

class Gaji_model extends CI_Model
{

    public $table = 'gaji';
    public $id = 'id_gaji';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        require APPPATH.'libraries/phpmailer/src/Exception.php';
        require APPPATH.'libraries/phpmailer/src/PHPMailer.php';
        require APPPATH.'libraries/phpmailer/src/SMTP.php';
                 
    }

    function email($subject,$isi,$emailtujuan)
    {
         // PHPMailer object
                    $response = false;
                    $mail = new PHPMailer();
                   
                    // SMTP configuration
                    $mail->isSMTP();
                    $mail->Host     = 'oblonger.com'; //sesuaikan sesuai nama domain hosting/server yang digunakan
                    $mail->SMTPAuth = true;
                    $mail->Username = 'admin@oblonger.com'; // user email
                    $mail->Password = 'F@t4yaku77'; // password email
                    $mail->SMTPSecure = 'ssl';
                    $mail->Port     = 465;
            
                    $mail->setFrom('admin@oblonger.com'); // user email
                    $mail->addReplyTo(''); //user email
            
                    // Add a recipient
                    $mail->addAddress($emailtujuan); //email tujuan pengiriman email
            
                    // Email subject
                    $mail->Subject = $subject; //subject email
            
                    // Set email format to HTML
                    $mail->isHTML(true);
            
                    // Email body content
                    $mailContent = $isi; // isi email
                    $mail->Body = $mailContent;                    
                    
                    // Send email
                    $mail->send();

        
            
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_gaji', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('nik', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_gaji', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('nik', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Gaji_model.php */
/* Location: ./application/models/Gaji_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-03 07:54:31 */
/* http://harviacode.com */