<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gaji_model extends CI_Model
{

    public $table = 'gaji';
    public $id = 'id_gaji';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function email($subject,$isi,$emailtujuan)
    {
        $config['protocol'] = 'smtp';
        $config['smtp_host'] = 'ssl://smtp.gmail.com';
        $config['smtp_port'] = '465';
        $config['smtp_user'] = 'tiananugerah14@gmail.com';
        $config['smtp_pass'] = 'tianganteng'; //ini pake akun pass google email
        $config['mailtype'] = 'html';
        $config['charset'] = 'iso-8859-1';
        $config['wordwrap'] = 'TRUE';
        $config['newline'] = "\r\n";
  
        $this->load->library('email', $config);
        $this->email->initialize($config);
  
        $this->email->from('tiananugerah14@gmail.com');
        $this->email->to($emailtujuan);
        $this->email->subject($subject);
        $this->email->message($isi);
        $this->email->set_mailtype('html');
        $this->email->send();	
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_gaji', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('nik', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_gaji', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('nik', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Gaji_model.php */
/* Location: ./application/models/Gaji_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-03 07:54:31 */
/* http://harviacode.com */