<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Konfirmasi_model extends CI_Model
{

    public $table = 'gaji';
    public $id = 'id_pekerjaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Pekerjaan_model.php */
/* Location: ./application/models/Pekerjaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-02 11:43:24 */
/* http://harviacode.com */